def incrypt(string):
    #change your incryption symbols here(below)
    def alt(i):
        if i=='a':
            return "2@"
        if i=='A':
            return "^6^"
        elif i=='b':
            return "22"
        elif i=='B':
            return "^6"
        elif i=='c':
            return "222"
        elif i=='C':
            return "2@2"
        elif i=='d':
            return "3"
        elif i=='D':
            return "@3%"
        elif i=='e':
            return "33"
        elif i=='E':
            return "3^*"
        elif i=='f':
            return "333"
        elif i=='F':
            return "*9)&"
        elif i=='g':
            return "4"
        elif i=='G':
            return "%$3"
        elif i=='h':
            return "44"
        elif i=='H':
            return "g&6"
        elif i=='i':
            return "444"
        elif i=='I':
            return "Mi%4"
        elif i=='j':
            return "5"
        elif i=='J':
            return "&*1"
        elif i=='k':
            return "55"
        elif i=='K':
            return "**&"
        elif i=='l':
            return "(?3"
        elif i=='L':
            return "555"
        elif i=='m':
            return "6"
        elif i=='M':
            return "j*u@"
        elif i=='n':
            return "66"
        elif i=='N':
            return "+00"
        elif i=='o':
            return "666"
        elif i=='O':
            return "33*j"
        elif i=='p':
            return "I%gf?"
        elif i=='P':
            return "7"
        elif i=='q':
            return "77"
        elif i=='Q':
            return ":lkY6"
        elif i=='r':
            return "777"
        elif i=='R':
            return "U&&"
        elif i=='s':
            return "7777"
        elif i=='S':
            return "Ii8*-"
        elif i=='t':
            return "8"
        elif i=='T':
            return "m%%1#"
        elif i=='u':
            return "asse#"
        elif i=='U':
            return "88"
        elif i=='v':
            return "Ko%ji"
        elif i=='V':
            return "888"
        elif i=='w':
            return "9"
        elif i=='W':
            return "3=%^"
        elif i=='x':
            return "99"
        elif i=='X':
            return "3&&fg"
        elif i=='y':
            return "999"
        elif i=='Y':
            return "Gh%e44"
        elif i=='z':
            return "9999"
        elif i=='Z':
            return "da-)-90"
        elif i==' ':
            return "!"
    #change your incryption symbols here(above)
    new='';
    for i in string:
        point=(alt(i))
        new=new+point
        
    return new
